apiVersion: v1
kind: Service
metadata:
  name: dragonfly
spec:
  type: {{ .Values.dragonfly.service.type }}

  selector:
    app: dragonfly

  ports:
    - name: redis
      port: {{ .Values.dragonfly.service.port }}
      targetPort: {{ .Values.dragonfly.service.port }}
