{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  type: {{ .Values.postgresql.service.type }}

  selector:
    app: postgres

  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
{{- end }}
