apiVersion: v1
kind: Service
metadata:
  name: target-app

spec:
  type: {{ .Values.targetApp.service.type }}

  selector:
    app: target-app

  ports:
    - name: http
      port: {{ .Values.targetApp.service.port }}
      targetPort: {{ .Values.targetApp.service.port }}
